### ISSUE TITLE
Please document how to run the tests

### ISSUE THREAD

**Issue by digitalronin** [brunoarueira/cryptopia#10]
Please could you provide some information on how to run the tests?

Currently, running "rake" results in a lot of errors about missing api key and secret values.

If I set dummy values for env vars API_KEY and API_SECRET, I get a different set of errors 'invalid base64'. 

Did you create the VCR files using your real Cryptopia API key and secret? If so, would it be possible to revoke that keypair and then add those values to the README/Rakefile, so that contributors can run the tests?

Failing that, some detail about how we could create our own VCR files would be helpful.

**Comment by brunoarueira** [comment]
@digitalronin I need to do that! I'll take a look at the weekend, probably.

Yes, I did! I'll think a better way to run the tests, since cryptopia does not offer a test environment.

**Comment by brunoarueira** [comment]
Since cryptopia announced bankruptcy on https://cryptopia.co.nz/, I'll archive this project.
