### ISSUE TITLE
How to determine no. of records with pagination ?

### ISSUE THREAD

**Issue by ZenMilan** [brunoarueira/cryptopia#11]
As per api documentation for Cryptopia exchange, for collections endpoints we have a 'count' optional param with default value of 100. How api knows pagination or is there any other way to fetch distinct collections with count and without pagination.
Eg. 
Say first request for trade_history has count=15 ie. call to trade_history(count=15),
if user has 200 trade_history records, on next call to trade_history(count=15), How api is supposed to return records after first  request ie. 15 to 30. I'm little bit confused. Thank you.

**Comment by brunoarueira** [comment]
Since cryptopia announced bankruptcy on https://cryptopia.co.nz/, I'll archive this project.
