### ISSUE TITLE
Implement Private API

### ISSUE THREAD

**Issue by brunoarueira** [brunoarueira/cryptopia#3]
https://www.cryptopia.co.nz/Forum/Thread/256

**Comment by nofxx** [comment]
Tô tentando, tá foda... só da parametros ñ batem com assinatura...

https://gist.github.com/nofxx/9b2ea3f3a0629fd7012cd4610ddd335d

Valeu pela gem!

**Comment by nofxx** [comment]
Consegui man, tem q decodar sem hexa.
E tem q decodar a secret tb.

```
        uri = CGI.escape(url + method).downcase
        nonce = Time.now.to_i.to_s
        base64 = Base64.strict_encode64(Digest::MD5.digest(params.to_json))
        sign = OpenSSL::HMAC.digest(
          'SHA256',
          Base64.strict_decode64(secret),
          apikey + 'POST' + uri + nonce + base64
        )
        sign64 = Base64.strict_encode64(sign)
        auth = "amx #{apikey}:#{sign64}:#{nonce}"

```

**Comment by brunoarueira** [comment]
@nofxx Tive problema parecido, só que comigo o que ocorreu foi porque não estava enviando o content type como json. Porém já consegui implementar alguns endpoints da parte private, só não enviei ainda um pr. Outra coisa não usei o strict_decode64 ou strict_encode64, vou ver a diferença.

**Comment by nofxx** [comment]
Tem que usar o strict, senão pode sair "\n" como caracter... 
Aliás, acho q o certo seria o #urlsafe_encode64 ...

https://ruby-doc.org/stdlib-2.1.3/libdoc/base64/rdoc/Base64.html
